name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Enable corepack (yarn 4)
        run: corepack enable

      - name: Grant access to package registry
        run: |
          yarn config set npmScopes.dhruv-m-patel.npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmScopes.dhruv-m-patel.npmAlwaysAuth true
          yarn config set npmScopes.dhruv-m-patel.npmAuthToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          CI: true

      - name: Install packages
        run: yarn install --immutable

      - name: Verify Code formatting
        run: yarn ci:lint

      - name: Typecheck
        run: yarn turbo run typecheck

      - name: Build app
        run: yarn ci:build

      - name: Run tests
        run: yarn ci:test
